# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ec1ed779563db26036ff527db90d7d0728837e998967b0eb1f67806ce84f7b0149b741ea113a98619a571ba9e52ace06b19c5d9fdfe92a807e22db881dfb92

test:
  secret_key_base: 87a6f9080b1c8f8a7f5b34fd0b4d1214c2ed020d80a8557e7cca8a394420f18a27f30881c922f97d1fa82de88e1c148ce2dac7ebf0cd8dc41ce21dc2ef19f5fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
